#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("conseilMoi.Resource", IsApplication=true)]

namespace conseilMoi
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::conseilMoi.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::conseilMoi.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::conseilMoi.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_custom_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Historique = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int iconeTest = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Profil = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Scan = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Suggestions = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Synthese = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070018
			public const int button1 = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int button2 = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int button3 = 2131165210;
			
			// aapt resource value: 0x7f070028
			public const int contentFrame = 2131165224;
			
			// aapt resource value: 0x7f070007
			public const int imageViewAvertissementAvertissement = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int imageViewAvertissementConseil = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int imageViewAvertissementHistorique = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int imageViewAvertissementProfil = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int imageViewAvertissementScann = 2131165189;
			
			// aapt resource value: 0x7f07000f
			public const int imageViewConseilAvertissement = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int imageViewConseilConseil = 2131165198;
			
			// aapt resource value: 0x7f07000c
			public const int imageViewConseilHistorique = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int imageViewConseilProfil = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int imageViewConseilScann = 2131165197;
			
			// aapt resource value: 0x7f070016
			public const int imageViewHistoriqueAvertissement = 2131165206;
			
			// aapt resource value: 0x7f070015
			public const int imageViewHistoriqueConseil = 2131165205;
			
			// aapt resource value: 0x7f070013
			public const int imageViewHistoriqueHistorique = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int imageViewHistoriqueProfil = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int imageViewHistoriqueScann = 2131165204;
			
			// aapt resource value: 0x7f070020
			public const int imageViewProduitAvertissement = 2131165216;
			
			// aapt resource value: 0x7f07001f
			public const int imageViewProduitConseil = 2131165215;
			
			// aapt resource value: 0x7f07001d
			public const int imageViewProduitHistorique = 2131165213;
			
			// aapt resource value: 0x7f07001c
			public const int imageViewProduitProfil = 2131165212;
			
			// aapt resource value: 0x7f07001e
			public const int imageViewProduitScann = 2131165214;
			
			// aapt resource value: 0x7f070027
			public const int imageViewProfilAvertissement = 2131165223;
			
			// aapt resource value: 0x7f070026
			public const int imageViewProfilConseil = 2131165222;
			
			// aapt resource value: 0x7f070024
			public const int imageViewProfilHistorique = 2131165220;
			
			// aapt resource value: 0x7f070023
			public const int imageViewProfilProfil = 2131165219;
			
			// aapt resource value: 0x7f070025
			public const int imageViewProfilScann = 2131165221;
			
			// aapt resource value: 0x7f070017
			public const int linearLayout1 = 2131165207;
			
			// aapt resource value: 0x7f07001b
			public const int linearLayout2 = 2131165211;
			
			// aapt resource value: 0x7f070022
			public const int linearLayoutBilanDesCirters = 2131165218;
			
			// aapt resource value: 0x7f070021
			public const int linearLayoutProfile = 2131165217;
			
			// aapt resource value: 0x7f070002
			public const int menuAvertissement = 2131165186;
			
			// aapt resource value: 0x7f07000a
			public const int menuConseil = 2131165194;
			
			// aapt resource value: 0x7f070011
			public const int menuHistorique = 2131165201;
			
			// aapt resource value: 0x7f070008
			public const int textView1 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int textView2 = 2131165193;
			
			// aapt resource value: 0x7f070001
			public const int textViewAvertissementTexte = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int textViewAvertissementTitre = 2131165184;
			
			// aapt resource value: 0x7f070010
			public const int textViewHistoriqueTitre = 2131165200;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Avertissement = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Conseil = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Historique = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Produit = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Profil = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int zxingscanneractivitylayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int zxingscannerfragmentlayout = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
